### PR TITLE
Rename facet arguments to filter

### PR DESCRIPTION
**Pull request by jazairi**
#### Why these changes are being introduced:

'Filter' more accurately describes what the facet args do.

#### Relevant ticket(s):

* https://mitlibraries.atlassian.net/browse/TIMX-177

#### How this addresses that need:

This renames every incidence of 'facet' to 'filter' to match the corresponding change in the TIMDEX API.

#### Side effects of this change:

Once the change is made in TIMDEX, we will need to reload the schema. Tests will fail until the change goes live in prod, so we will want to time this carefully.

#### Developer

- [x] All new ENV is documented in README
- [x] All new ENV has been added to Heroku Pipeline, Staging and Prod
- [ ] ANDI or Wave has been run in accordance to
      [our guide](https://mitlibraries.github.io/guides/basics/a11y.html) and
      all issues introduced by these changes have been resolved or opened as new
      issues (link to those issues in the Pull Request details above)
- [ ] Stakeholder approval has been confirmed (or is not needed)

#### Code Reviewer

- [x] The commit message is clear and follows our guidelines
      (not just this pull request message)
- [x] There are appropriate tests covering any new functionality
- [x] The documentation has been updated or is unnecessary
- [x] The changes have been verified
- [x] New dependencies are appropriate or there were no changes

#### Requires database migrations?

NO

#### Includes new or updated dependencies?

NO

### CODE REVIEW

**Comment by jazairi** [comment]
I wonder if we should temporarily point this at the review app for [the corresponding API PR](https://github.com/MITLibraries/timdex/pull/646) to make sure the tests pass. Thoughts, @JPrevost?

**Comment by JPrevost** [comment]
@jazairi I think we probably will need to refresh the locally cached schema in this app with the schema in that review app based on this process: https://github.com/MITLibraries/timdex-ui#updating-graphql-schema

**Comment by jazairi** [comment]
@JPrevost Yeah, the schema should be updated anyway since we've changed a bunch of descriptions recently.

**Comment by JPrevost** [comment]
@jazairi my assumption is that the tests are not tied to production so much as the cassettes need to be refreshed against an endpoint with the new schema _and_ the new schema needs to be cached here. Maybe.

**Comment by JPrevost** [comment]
@jazairi Oh I see you already included the schema update. I missed that part. Have you tried regenerating cassettes against the PR build endpoint? It's definitely a graphql validation error in the tests but I haven't looked at how the cassettes work in this app yet to confirm that's where the problem is for sure but it feels worth checking into if you haven't yet.

**Comment by jazairi** [comment]
@JPrevost Just finished regenerating cassettes and updated the schema to match the TIMDEX PR (https://github.com/MITLibraries/timdex/pull/646).

**Review by JPrevost — APPROVED** [review]

**Pull request merged**
