### PR TITLE
Document decision to use ADRs

### PR DESCRIPTION
**Pull request by jazairi**
#### Why these changes are being introduced:

We are about to make major architectural decisions about this application, and we need a framework for recording them.

#### Relevant ticket(s):

* https://mitlibraries.atlassian.net/browse/GDT-123

#### How this addresses that need:

This adds an initial architectural decision record (ADR) to confirm that we will use ADRs in this repo.

#### Side effects of this change:

Future significant architectural decisions should be documented as ADRs.

#### Developer

- [ ] All new ENV is documented in README
- [ ] All new ENV has been added to Heroku Pipeline, Staging and Prod
- [ ] ANDI or Wave has been run in accordance to
      [our guide](https://mitlibraries.github.io/guides/basics/a11y.html) and
      all issues introduced by these changes have been resolved or opened as new
      issues (link to those issues in the Pull Request details above)
- [x] Stakeholder approval has been confirmed (or is not needed)

#### Code Reviewer

- [ ] The commit message is clear and follows our guidelines
      (not just this pull request message)
- [ ] There are appropriate tests covering any new functionality
- [ ] The documentation has been updated or is unnecessary
- [ ] The changes have been verified
- [ ] New dependencies are appropriate or there were no changes

#### Requires database migrations?

NO

#### Includes new or updated dependencies?

NO

### CODE REVIEW

**Comment by jazairi** [comment]
I realized we didn't have ADRs set up for this repo, so I figured I'd get this out of the way in a separate PR before documenting the initial GDT decisions.

**Review by JPrevost — CHANGES_REQUESTED** [review]
I think we've normalized to include a .adr-dir file to put these in a subdirectory of `docs` rather than having them at the top level of `doc`.

https://github.com/MITLibraries/timdex/blob/main/.adr-dir

**Comment by jazairi** [comment]
@JPrevost Thanks, I'd forgotten about that!

**Review by JPrevost — APPROVED** [review]

**Review by matt-bernhardt — APPROVED** [review]
LGTM

**Pull request merged**
